[package]
name = "pcap-file-index"
version = "0.1.0"
authors = ["SEKINE, Hideki <sekineh@toyo.co.jp>"]

[dependencies]
pcap-file = "0.10.0"
serde = "1.0.70"
serde_derive = "1.0.70"
bincode = "1.0.1"
# log = "0.4.1"
# failure = "0.1.1"
# failure_derive = "0.1.1"

